name: landfall_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - dask
  - distributed
  - zarr
  - numcodecs
  - matplotlib
  - cartopy
  - cmocean
  - pillow
  - netcdf4
  - h5netcdf       # optional, alternative NetCDF backend
  - cfgrib         # optional, only if you need GRIB support
  - eccodes        # required by cfgrib
  - scipy          # required to regrid quivers on vector plot
